---
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - explicit_init
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - sorted_imports
excluded:
  - .build
  - BuildTools/.build
  - vendor/bundle
